name: circle_bottom_navigation
description: An animated, beauty and functional Bottom Navigation Bar you app.
version: 1.0.6
homepage: https://github.com/jeaanlucas/circle_bottom_navigation

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0
  analyzer: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
